// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIBaseURL() {
  return window['go']['main']['App']['GetAPIBaseURL']();
}

export function GetDesktopHTTPPortSetting() {
  return window['go']['main']['App']['GetDesktopHTTPPortSetting']();
}

export function SetDesktopHTTPPortSetting(arg1) {
  return window['go']['main']['App']['SetDesktopHTTPPortSetting'](arg1);
}
